spring:
  application:
    name: BrainDissecting
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/brain_dissecting?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:password}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    include-stacktrace: always
# https://doaj.org/article/0001d38c946a4231bae36435429a0853
doaj:
  api:
    subject: ${ARTICLE_SUBJECT:}
    pageSize: ${PAGE_SIZE:}
    url: "https://doaj.org/api/search/articles/{subject}?pageSize={pageSize}"


